//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RubikCube.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RubikCube.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #version 430 core
        ///in vec2 fragTexCoord;
        ///in vec3 fragPos;
        ///in vec3 fragNormal;
        ///in vec3 fragTangent;
        ///in vec3 fragBitangent;
        ///
        ///layout (std140, binding = 0) uniform Camera {
        ///    mat4 ViewProjectionMatrix;
        ///    vec3 CameraPos;
        ///};
        ///struct Light {
        ///    vec4 Pos;    
        ///    vec3 Ambient;
        ///    vec3 Diffuse;
        ///    vec3 Specular;
        ///    vec3 AttCoeff;
        ///};
        ///const int MAX_LIGHTS = 10;
        ///layout (std140, binding = 2) uniform Lights {
        ///    Light lights[MAX_LIGHTS];
        ///    float LightsCount;
        ///};
        ///struct Material { 
        ///    samp [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Fragment_glsl {
            get {
                return ResourceManager.GetString("Fragment_glsl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #version 430 core
        ///layout(location = 0) in vec3 vertPos;
        ///layout(location = 1) in vec2 vertTexCoord;
        ///layout(location = 2) in vec4 vertBones;
        ///layout(location = 3) in vec4 vertWeights;
        ///layout(location = 4) in vec3 vertNormal;
        ///layout(location = 5) in vec3 vertTangent;
        ///layout(location = 6) in vec3 vertBitangent;
        ///
        ///layout(std140, binding = 0) uniform Camera {
        ///    mat4 ViewProjectionMatrix;
        ///    vec3 CameraPos;
        ///};
        /////layout(std430, binding = 1) buffer Bones
        ///const int MAX_BONES_TRANSFORMS = 100;
        ///layout(s [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Vertex_glsl {
            get {
                return ResourceManager.GetString("Vertex_glsl", resourceCulture);
            }
        }
    }
}
